name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - run: |
          npm install
          ./scripts/release.sh
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            ./build/ios-clipboard-history-io-mobile.ipa
            ./build/android-clipboard-history-io-mobile.aab
